apiVersion: v1
data:
  service-graph: |
    defaults:
      fortio_cluster: gke_istio-testing-270515_asia-southeast1_istio-spike-1
      ingress_gateway_endpoint: x.x.x.x
    services:
    - cluster_context: context_string
      isEntrypoint: true
      name: a
      numRbacPolicies: 0
      numReplicas: 1
      responseSize: 1KiB
      type: http
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-30T06:15:40Z"
  labels:
    app: service-graph
  name: service-graph-config
  namespace: service-graph
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2020-04-30T06:15:40Z"
  labels:
    istio-injection: enabled
  name: service-graph
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2020-04-30T06:15:40Z"
  labels:
    app: service-graph
  name: a
  namespace: service-graph
spec:
  replicas: 1
  selector:
    matchLabels:
      name: a
  strategy: {}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      creationTimestamp: "2020-04-30T06:15:40Z"
      labels:
        name: a
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: a
        image: tahler/isotope-service:1
        name: mock-service
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
status: {}
